### ISSUE TITLE
Questions about task indicator and resource usage

### ISSUE THREAD

**Issue by edwhu** [AlbertTan404/RoLD#1]
Hi, thanks for open-sourcing the code!

1) Can you give more detail about the "task conditions" / "task indicator" in section 4.3 / 4.4? Is it just a one-hot encoding of the task? I think that if you embedded the language descriptions of the task, then tasks with similar text descriptions can get clustered together.  But I'm not sure what the task indicator is or how you are encoding it here. 

2) Can you give some detail about the resource usage and runtime of this codebase? Like how many GPUs, GPU memory, training time, etc.

**Comment by AlbertTan404** [comment]
Great questions! 
A1: We use DistilBERT to encode task descriptions into embeddings as mentioned in section 3.3. In our ablation experiment shows that the autoencoder without textual embeddings input achieves the best performance, as it tends to cluster on sub-task skills rather than similar textual inputs.
A2: We use a 4*V100 machine with a 108-cores CPU. It takes ~1 day for pre-training with DDP on 4 GPUs and ~350GBs memory, and ~4 hours for fine-tuning on a single GPU.

**Comment by edwhu** [comment]
Thank you!
